spring.application.name=MPIF
spring.shell.interactive.enabled=true
server.port=6544
server.error.include-message=always

server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=demoDemo
server.ssl.key-store-type=jks
server.ssl.key-alias=demo
server.ssl.key-password=demoDemo

logging.file.name=logs/mpif-app.log
logging.file.path=logs
logging.level.root=INFO
logging.level.com.ivir.mpif=INFO

spring.web.resources.chain.cache=false
spring.web.resources.cache.use-last-modified=false
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-store=true